### ISSUE TITLE
运行问题！！

### ISSUE THREAD

**Issue by yangtzelsl** [apachecn/AiLearning#378]
您好，关于推荐系统这一部分，基于item和基于user，程序是怎么运行的呢？哪几个文件属于一起的呀？当我直接运行RS-itemcf.py的时候，报错如下：
C:\software\Anaconda3\python.exe D:/python/MachineLearning-dev/src/py3.x/16.RecommenderSystems/RS-itemcf.py
  File "D:/python/MachineLearning-dev/src/py3.x/16.RecommenderSystems/RS-itemcf.py", line 3
    Created on 2015-06-22
             ^
SyntaxError: invalid syntax

Process finished with exit code 1
不知应当如何解决呢，请大神帮忙解答一下，感激不尽！！！

**Comment by yangtzelsl** [comment]
我查了一些资料，我使用的是python3源码里的推荐系统，用python3进行部署的，不过我发现源码中还是有很多python2的输出格式，我基本改正过来了，另还有部分不会修改，比如lambda匿名函数，以及
![image](https://user-images.githubusercontent.com/33994422/39907435-57d7b390-551b-11e8-96cb-f3dc546c4c44.png)
如图所示的相关调用，对此不是很熟悉，不知能否提供一份python3下的源码，以及相关执行步骤，谢谢！！！

**Comment by jiangzhonglian** [comment]
不好意思，暂时没时间更新这个推荐系统这一块，需要你自己想想办法
