### ISSUE TITLE
加入我们 - ApacheCN

### ISSUE THREAD

**Issue by jiangzhonglian** [apachecn/AiLearning#441]
http://ailearning.apachecn.org/join-us/ 

 ApacheCN 专注于优秀项目维护的开源组织

**Comment by zhaozengbin** [comment]
什么样的人才能加入一群呢？

**Comment by jiangzhonglian** [comment]
额。 一群？？ 我们的群应该都可以加吧？

**Comment by lisniuse** [comment]
群被拒绝加入了。我是numpy.org.cn 的创始人，希望可以换个友情链接。

**Comment by jiangzhonglian** [comment]
小哥哥加我QQ: 529815144
认识大佬是我们开源组织最乐意的事情。
很荣幸能和老哥交换友情链接
