### ISSUE TITLE
视频制作细节

### ISSUE THREAD

**Issue by Jiuyong** [apachecn/AiLearning#442]
在制作讲解视频时，对于屏幕，可否仅仅使用键盘来滚动屏幕，避免使用鼠标滚轮？
因为这样对于讲解者可能下意识的滚动屏幕，但是对于观看者来说，屏幕晃动的厉害，只能看个大概的图，而屏幕上的文字就别想认真看清楚了。

**Comment by jiangzhonglian** [comment]
谢谢小哥建议，尽量避免～
