### ISSUE TITLE
"/src/py3.x/ml/4.NaiveBayes/bayes.py" #line164 疑问

### ISSUE THREAD

**Issue by wtzhang95** [apachecn/AiLearning#450]
引自该文件164行：" # 可以理解为 1.单词在词汇表中的条件下，文件是good 类别的概率 也可以理解为 2.在整个空间下，文件既在词汇表中又是good类别的概率"

您好，我对这里的p1Vec意义有疑问，我认为应该是在文件是good类别的前提下，对应位置(index)的单词出现在文档中的概率.

**Comment by jiangzhonglian** [comment]
是的，你说的没毛病，就是这个意思
