### ISSUE TITLE
读取文件的函数loadDataSet(file_name)代开后没有关闭

### ISSUE THREAD

**Issue by guokaiSama** [apachecn/AiLearning#477]
比如：https://github.com/apachecn/AiLearning/blob/dev/src/py2.x/ml/5.Logistic/logistic.py
中的loadDataSet(file_name)函数
其他涉及到读取文件的地方都这这个问题
可以改成with open as:
或者读取完毕后关闭文件

**Comment by jiangzhonglian** [comment]
额。谢谢老哥，这个程序只是图个方便。
如果可以帮忙提交一下PR，你修改后的版本
