### ISSUE TITLE
第7章 AdaBoost plot_roc 问题

### ISSUE THREAD

**Issue by yiranxiada** [apachecn/AiLearning#486]
test()函数里面的执行句
plot_roc(agg_class_est, class_labels)应为plot_roc(agg_class_est.T, class_labels),否则是无法画出ROC曲线的

**Comment by jiangzhonglian** [comment]
python 是 什么版本的？

**Comment by yiranxiada** [comment]
Python 3.6

**Comment by yiranxiada** [comment]
得到的agg_class_est是一个m*1维的矩阵，需对其转置后再进行argsort()等一系列操作，不然就要改为argsort(axis=0)，
同时在索引循环那改成
for index in sorted_indicies.tolist():
        if class_labels[index[0]] == 1.0:

**Comment by jiangzhonglian** [comment]
老哥，你介意提交一下Pull Request 么？
把你修改的几个方案可以补充进来
