### ISSUE TITLE
LSTM深入浅出的好文这篇 blog 链接已挂

### ISSUE THREAD

**Issue by Sunjk21** [apachecn/AiLearning#499]
第2部分-深度学习基础-深度学习必学下第4个链接 _LSTM深入浅出的好文: https://blog.csdn.net/roslei/article/details/61912618_ ，此链接不可用。

**Comment by jiangzhonglian** [comment]
额。。。。这个嘛！ 我有空整理到GitHub 上门来吧。
作者删除内容很尴尬。。。。
