### ISSUE TITLE
为什么logistic 回归的sigmoid函数采用tanh函数画出的图明显不对

### ISSUE THREAD

**Issue by todaymycode** [apachecn/AiLearning#525]
如果采用
def sigmoid2(x):
    return 2 * 1.0 / (1 + exp(-2 * x)) - 1
形式定义sigmoid函数，回归系数会和采用
def sigmoid(x):
    return 1.0 / (1 + np.exp(-x))
定义的相差很大，即使迭代次数增加也一样，所以画出来的图的分界线一点都没有将点分开，为什么？

**Comment by todaymycode** [comment]
![Figure_1](https://user-images.githubusercontent.com/44046443/58965840-cee5bf80-87e3-11e9-8639-41a294241d0b.png)
这是采用tanh函数定义画出来的图，迭代了5000次，但是图明显不对啊

**Comment by jiangzhonglian** [comment]
主要是看取值区间。。
激活函数的用途都差不多
