### ISSUE TITLE
机器学习实战第四章rss源失效

### ISSUE THREAD

**Issue by swjtulwy** [apachecn/AiLearning#526]
第四章贝叶斯分类的代码中，访问不了以下两个源：
http://newyork.craigslist.org/stp/index.rss
http://sfbay.craigslist.org/stp/index.rss
404 ERROR

**Comment by jiangzhonglian** [comment]
说明接口关闭了，这个我们控制不了。
学明白理论就行！ 无法避免的还是跳过。
