### ISSUE TITLE
KNN教程无法运行啊

### ISSUE THREAD

**Issue by swtlovewtt** [apachecn/AiLearning#527]
E:\>python E:\Github\AiLearning\src\py2.x\ml\2.KNN\kNN.py
Traceback (most recent call last):
  File "E:\Github\AiLearning\src\py2.x\ml\2.KNN\kNN.py", line 298, in <module>
    handwritingClassTest()
  File "E:\Github\AiLearning\src\py2.x\ml\2.KNN\kNN.py", line 267, in handwritingClassTest
    trainingFileList = listdir('data/2.KNN/trainingDigits')  # load the training set
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'data/2.KNN/trainingDigits'

**Comment by swtlovewtt** [comment]
'data/2.KNN/trainingDigits'
这个文件找不到

**Comment by swtlovewtt** [comment]
找到原因了,是相对路径有问题

**Comment by jiangzhonglian** [comment]
要打屁股

**Comment by daipozhi** [comment]
hi,"Ai" should be "AI","Ailearning" should be "AI-Learning",am I right?

**Comment by jiangzhonglian** [comment]
yes

**Comment by gosser123** [comment]
> yes

请问将data文件夹放在AILearning下，使用相对路径应该怎样修改，不想使用绝对路径
