### ISSUE TITLE
麻烦优化一下函数和变量的命名，太垃圾了

### ISSUE THREAD

**Issue by lopince** [apachecn/AiLearning#532]
如题

**Comment by jiangzhonglian** [comment]
额？这个命名如果我没猜错，应该是这本书的原创作者写的，应该不垃圾吧？

如果非要改，不知道你想改成什么样子，能给你一个案例吗？

**Comment by lopince** [comment]
原作者的就一定好吗？
很多函数名和函数实现的功能，都词不达意，容易造成confuses

**Comment by jiangzhonglian** [comment]
小哥哥，我也想了很久，要不你看这样如何，你来帮忙优化优化？
