### ISSUE TITLE
关于随机森林有个问题

### ISSUE THREAD

**Issue by guohaoyuan** [apachecn/AiLearning#534]
AiLearning/src/py2.x/ml/7.RandomForest/randomForest.py 第111行
 gini += float(size)/D * (proportion * (1.0 - proportion)) # 个人理解：计算代价，分类越准确，则 gini 越小
是不是少了一个2，见下：
 gini += float(size)/D * (2*proportion * (1.0 - proportion)) # 个人理解：计算代价，分类越准确，则 gini 越小

**Comment by NuanBaobao** [comment]
没有吧 感觉是对的
