### ISSUE TITLE
data文件夹

### ISSUE THREAD

**Issue by acclea** [apachecn/AiLearning#545]
大佬，是为了考验我删除了data文件夹，还是误操作了，在线等，还是比较着急的

**Comment by ryuzheng** [comment]
> 大佬，是为了考验我删除了 data 文件夹，还是误操作了，在线等，还是比较着急的

https://github.com/apachecn/data 

你说的应该搬到这个repo了。

**Comment by acclea** [comment]
好的，谢谢了

**Comment by jiangzhonglian** [comment]
主要是这个项目太大了，很多人都下载不下来，所以我单独打包

数据下载地址：https://github.com/apachecn/data/tree/master/机器学习
