### ISSUE TITLE
逻辑回归weighs的推倒

### ISSUE THREAD

**Issue by yzz-ihep** [apachecn/AiLearning#552]
weighs的梯度推导过程应该是根据最大似然函数求极值来的吧；要求的是最大似然函数的极大值，所以称为梯度上升；如果给极大似然函数加负号就是梯度下降了。所求的梯度不是z=w0*x0+w1*x1...的梯度。这是我对《机器学习实战》的理解。

**Comment by jiangzhonglian** [comment]
我觉得上升和下降只是一个方向问题
