### ISSUE TITLE
chp6 svm alphas = mat(zeros((m, 1)))

### ISSUE THREAD

**Issue by fish-work** [apachecn/AiLearning#553]
alphas = mat(zeros((m, 1)))
fXi = float(multiply(alphas, labelMat).T*(dataMatrix*dataMatrix[i, :].T)) + b

alphas 为 0 向量，fxi=0，无法迭代，是不是alphas的初始值为非零向量，例如：全1向量？

**Comment by jiangzhonglian** [comment]
print 试试
