### ISSUE TITLE
Which kind of model is better for keyword-set classification?

### ISSUE THREAD

**Issue by guotong1988** [apachecn/AiLearning#566]
There exists a similar task that is named text classification.

But I want to find a kind of model that the inputs are keyword set. And the keyword set is not from a sentence.

For example:
```
input ["apple", "pear", "water melon"] --> target class "fruit"
input ["tomato", "potato"] --> target class "vegetable"
```

Thank you.

**Comment by jiangzhonglian** [comment]
你的输入，我理解为一个长文本，而其中的keyword 只是一个词而已

你要做的就是用词向量(Embedding)，就可以解决你的问题
input + Embedding + 全连接层 Dense  + 全连接层 Dense  + output

中间你可以自己加入一下优化方法
