### ISSUE TITLE
FP growth中这一段有错误？

### ISSUE THREAD

**Issue by Tentabrella** [apachecn/AiLearning#568]
从FP树中挖掘出频繁项集 这一部分中

> 去掉FP树中的t节点，得到条件模式基<左边路径,左边是值>[z,x,y,s,t]:2，[z,x,y,r,t]:1 。条件模式基的值取决于末尾节点 t ，因为 t 的出现次数最小，一个频繁项集的支持度由支持度最小的项决定。所以 t 节点的条件模式基的值可以理解为对于以 t 节点为末尾的前缀路径出现次数。

“得到条件模式基<左边路径,左边是值>”这儿应该写成“左边路径，右边是值”吧

**Comment by jiangzhonglian** [comment]
是的 是的，写错了，能帮忙提交一下PR吗？

**Comment by jiangzhonglian** [comment]
已经修改更新了，辛苦了
