### ISSUE TITLE
显示出现乱码

### ISSUE THREAD

**Issue by seekincs** [apachecn/AiLearning#571]
学习文档的文章显示不出来。
![bad_encoding](https://user-images.githubusercontent.com/42036440/75102823-f9ef9800-562c-11ea-9a2b-abefbed31372.png)

**Comment by jiangzhonglian** [comment]
显示正常
地址: https://ailearning.apachecn.org/#/docs/ml/1.机器学习基础

![image](https://user-images.githubusercontent.com/9199175/76648426-a4f2d200-6599-11ea-9637-0dfefb06080e.png)
