### ISSUE TITLE
第二章 KNN

### ISSUE THREAD

**Issue by ybshaw** [apachecn/AiLearning#579]
请问可以提供下KNN项目里的数据集吗，我看给的链接里已经找不到那个文件了，谢谢

**Comment by Chochenxi** [comment]
详情见附件





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ybshaw"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月25日(星期三) 上午10:57
收件人:&nbsp;"apachecn/AiLearning"<AiLearning@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[apachecn/AiLearning] 第二章 KNN (#579)





 
请问可以提供下KNN项目里的数据集吗，我看给的链接里已经找不到那个文件了，谢谢

**Comment by jiangzhonglian** [comment]
数据下载地址： https://github.com/apachecn/AiLearning/issues/580
