### ISSUE TITLE
py3.x里的Apriori实现并不支持python3， 而是python2？

### ISSUE THREAD

**Issue by Zerichen** [apachecn/AiLearning#581]
用python3.6 运行 py3.x/ml/11.Apriori/apriori.py 有类似`has_key()`, `zerodivisionerror`类似的报错，用python2.7就正常output `frozenset()`数据集。想请问下py.3x repository底下的代码实现是否还未更新成python3?

**Comment by jiangzhonglian** [comment]
3.x 目前没更新，主要是API的修改，自己百度查一下就行
