### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by Harvey9610** [apachecn/AiLearning#593]
Can the code be updated to fit Python3?

**Comment by jiangzhonglian** [comment]
目前暂时没时间去迭代 3.x，有以下几点原因: 

* 个人觉得学好 2.x 版本的代码就够你学习用
* 没太必要去纠结3.x版本的代码，这个只是一个接口升级而已
* 以后工作，基本上会直接使用专业 sklearn/pytorch/kears 的 API接口就行

---

当然欢迎喜欢挑战自己的人，可以去更新3.x 版本的最新接口
