### ISSUE TITLE
贡献者

### ISSUE THREAD

**Issue by jiangzhonglian** [apachecn/ailearning#595]
## 项目负责人

> Ml 第一期 (2017-02-27)

* [@片刻](https://github.com/jiangzhonglian)
* [@那伊抹微笑](https://github.com/wangyangting)
* [@瑶妹](https://github.com/chenyyx)

> Ml 第二期 (2017-08-14)

* [@片刻](https://github.com/jiangzhonglian)
* [@那伊抹微笑](https://github.com/wangyangting)
* [@瑶妹](https://github.com/chenyyx)
* [@Mike](https://github.com/mikechengwei)

> Ml 第三期 (2018-04-16)

* [@片刻](https://github.com/jiangzhonglian)
* [@飞龙](https://github.com/wizardforcel)

## 项目贡献者

> Ml 第一期 (2017-02-27)

* [@侯法超](https://github.com/geekidentity)
* [@hello19883](https://github.com/hello19883)
* [@徐鑫](https://github.com/sheepmen)
* [@ibe](https://github.com/highfei2011)

> Ml 第二期 (2017-08-14)

* [@Arithmetic](https://github.com/LeeMoonCh)
* [@Veyron C](https://github.com/caopeirui)
* [@Cugtyt](https://github.com/Cugtyt)
* [@BBruceyuan](https://github.com/hey-bruce)

> Ml 第三期 (2018-04-16)

## 群管理员换届

* [@瑶妹](https://github.com/chenyyx)
* [@飞龙](https://github.com/wizardforcel)
* [@片刻](https://github.com/jiangzhonglian)
* [@伪文艺.](https://github.com/Watermelon233)
* [@那伊抹微笑](https://github.com/wangyangting)
* [@LAMDA-健忘症]() 永久留任-非常感谢对群的贡献

> Ml 第四届 (2019-06-01)

* [佛学爱好者]()
* [楚盟]()
* [codefun007.xyz]()
* [大鱼-群花-声优]()
* [大海]()
* [Edge]()
* [if only]()
* [李孟禹]()
* [平静]()
* [任务做不完]()
* [仁礼智爱]()
* [园时空守望者@]()
* [坐看云起]()
* [阿花君霸占路人]()
* [烦焖鸡]()
* [古柳-DesertsX]()
* [青鸟(服务员)]()
* [小明教主]()
* [zhiqing]()
* [SrL.z]()

> Ml 第三届 (2019-01-01)

* [只会喊666的存在]()
* [codefun007.xyz]()
* [荼靡]()
* [大鱼]()
* [青鸟]()
* [古柳-DesertsX]()
* [Edge]()
* [Alluka]()
* [不发篇paper不改名片]()
* [FontTian]()
* [Bigjing]()
* [仁 礼 智 爱]()
* [可啪的小乖受]()
* [老古董]()
* [时空守望者]()
* [我好菜啊]()
* [Messi 19]()
* [萌Jay小公举]()

> Ml 第二届 (2018-07-04)

* [@张假飞]()
* [@李孟禹]()
* [@小明教主]()
* [@平淡的天]()
* [@凌少skierゞ]()
* [@じ☆νЁ坐看云起]()
* [古柳-DesertsX]()
* [woodchuck]()
* [自由精灵]()
* [楚盟]()
* [99杆清台]()
* [时空守望者@]()
* [只想发论文的渣渣]()
* [目标: ml劝退专家]()

> Ml 第一届 (2017-09-01)

* [@易漠]()
* [@Mike](https://github.com/mikechengwei)
* [@Books]()
* [@李孟禹]()
* [@张假飞]()
* [@Glassy]()
* [@红色石头]()
* [@微光同尘]()

**Comment by wizardforcel** [comment]
以后贡献者一律写到项目里面，否则无法备份
