### ISSUE TITLE
bayes  问题 咨询

### ISSUE THREAD

**Issue by FANBOCHENG** [apachecn/AiLearning#601]
posting_list = [
        ['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
        ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
        ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
        ['stop', 'posting', 'stupid', 'worthless', 'gar e'],
        ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
        ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]
    class_vec = [0, 1, 0, 1, 0, 1]  # 1 is 侮辱性的文字, 0 is not

posting_list size =7
class_vec size =  6  

这里是不是 有问题

**Comment by jiangzhonglian** [comment]
你再数数？

**Comment by FANBOCHENG** [comment]
好吧我知道了
