### ISSUE TITLE
添加 上一页/下一页 按钮

### ISSUE THREAD

**Issue by doglex** [apachecn/AiLearning#615]
临时用油猴脚本解决  https://github.com/doglex/monkeyScript/blob/main/QuickPageHelper.js
![111](https://user-images.githubusercontent.com/7918755/100370882-eea91d00-3041-11eb-9164-c3ef1d97abaf.PNG)

**Comment by jiangzhonglian** [comment]
@wizardforcel  这个js 你懂嘛？ 我看不太懂怎么添加
@doglex  小哥哥，是否方便提交一个pull requests? 我来合并，我不太懂 js

**Comment by wizardforcel** [comment]
哪个上下页的按钮能不能做好看点。。。

**Comment by wizardforcel** [comment]
好，我想想怎么设计更好看一点
