### ISSUE TITLE
it is excellent project,thanks to all guys.

### ISSUE THREAD

**Issue by 1qiqiqi** [apachecn/AiLearning#628]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jiongstudeng** [comment]
您好，您的邮件已收到，我将尽快给您回复。

**Comment by crazyyanchao** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by sumingfirst** [comment]
你的邮件我受到非常感谢配合

**Comment by jiangqingfeng1992** [comment]
您好！
      我已收到您的邮件，谢谢你的来信，我会尽快处理的。

**Comment by pc-mysql** [comment]
您的来信我已收到，将尽快给您回复，谢谢，pc

**Comment by ABromide** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zhangmman** [comment]
你好，您的邮件我已收到！！！

**Comment by jiangzhonglian** [comment]
卧槽。。各位都正常点。。
