### ISSUE TITLE
在线阅读（Gitee）打不開

### ISSUE THREAD

**Issue by ng-fukgin** [apachecn/ailearning#629]
[在线阅读（Gitee）](https://apachecn.gitee.io/ailearning) 打不開 ，顯示404 Not Found

**Comment by sumingfirst** [comment]
你的邮件我受到非常感谢配合

**Comment by kxkxkxl** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by pc-mysql** [comment]
您的来信我已收到，将尽快给您回复，谢谢，pc

**Comment by zhangmman** [comment]
你好，您的邮件我已收到！！！

**Comment by jiongstudeng** [comment]
您好，您的邮件已收到，我将尽快给您回复。

**Comment by ABromide** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wizardforcel** [comment]
@jiangzhonglian 看看这些邮件回复，可以当作一种新的宣传方式

**Comment by sanxincao** [comment]
gitee挂了
