### ISSUE TITLE
朴素贝叶斯实战例子疑惑

### ISSUE THREAD

**Issue by zhijs** [apachecn/ailearning#631]
朴素贝叶斯实战例子这里是写错了吗？这里概率应该是乘法而不是加法吗？
[代码路径](https://github.com/apachecn/ailearning/blob/5d89832ce283d6a269cee32c86deb11aafa6ca03/src/py3.x/ml/4.NaiveBayes/bayes.py#L165)

<img width="507" alt="image" src="https://user-images.githubusercontent.com/18703797/197711972-bb2abaa6-d168-4ec6-9f9e-f3b716784930.png">

**Comment by jiangzhonglian** [comment]
求log, 不就是为了乘法变加分吗？

**Comment by zhijs** [comment]
> 哇，懂了，原来如此， 感谢大佬解答～，我说为啥之前算概率的时候为啥取了 log, 还有一点小小的请教是，我理解这个 p1vec, p0vec 是该单词在非侮辱类型文本和侮辱性文本出现的条件概率， 因为 bayes 公式是还有一个分母 p(x, y) 单词表示整体出现的概率（不知道有没有理解错），这里是因为分母都一样，所以只比较分子是吗？

看到文档里是这样的逻辑了，打扰了，感谢～
