### ISSUE TITLE
数据分析文档描述错误

### ISSUE THREAD

**Issue by flca267** [apachecn/ailearning#632]
具体位置为 数据分析 -> 03. Numpy -> Numpy 数据及其索引
该 md 中 **二维花式索引** 中
Out[48]: 和 In [49]: 中间
返回的是最后三行的第1，3，5列。
应为
返回的是最后三行的第1，3，6列。

**Comment by Ezio660914** [comment]
您好，邮件已收到，我会尽快查收。Fang

**Comment by flca267** [comment]
md 文件位置为：ailearning/docs/da/031.md

**Comment by flca267** [comment]
在同一页
In [51]:
`condition = array([0,1,1,0,1],
                 dtype=bool)`
应为
`condition = array([0,1,1,0,1,0],
                 dtype=bool)`

**Comment by jiangzhonglian** [comment]
谢谢！已修复
