### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by ds-giao** [apachecn/ailearning#643]
大佬您好，可以提供一下垃圾邮件分类的数据集spam和ham吗，感谢

**Comment by zyuegege** [comment]
这是来自张越的自动回复邮件。您好，你的邮件已经收到，我会尽快给您回复。

**Comment by jiangzhonglian** [comment]
详情地址看: https://github.com/apachecn/ailearning/discussions/642

gitee 下载地址：
资料来源: Machine Learning in Action(机器学习实战-个人笔记)
统一数据地址: https://gitee.com/apachecn/data
书籍下载地址: https://gitee.com/apachecn/data/tree/master/book
机器学习下载地址: https://gitee.com/apachecn/data/tree/master/机器学习
深度学习数据地址: https://gitee.com/apachecn/data/tree/master/深度学习
推荐系统数据地址: https://gitee.com/apachecn/data/tree/master/推荐系统

github 下载地址：
资料来源: Machine Learning in Action(机器学习实战-个人笔记)
统一数据地址: https://github.com/apachecn/data
书籍下载地址: https://github.com/apachecn/data/tree/master/book
机器学习下载地址: https://github.com/apachecn/data/tree/master/机器学习
深度学习数据地址: https://github.com/apachecn/data/tree/master/深度学习
推荐系统数据地址: https://github.com/apachecn/data/tree/master/推荐系统
更新时间 2020-05-05
