### ISSUE TITLE
第11章_Apriori算法

### ISSUE THREAD

**Issue by SydCS** [apachecn/ailearning#647]
# Apriori 算法的使用
Typo: ”燃尽后对生下来的集合进行组合以声场包含两个元素的项集。“
应为 ”然后对剩下来的集合进行组合以生成包含两个元素的项集。“

**Comment by SydCS** [comment]
另外，请问这里面拍的两张图来自哪本书呢，谢谢！

**Comment by jiangzhonglian** [comment]
机器学习实战
